[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.vscode|_build|buck-out|build|dist|.*\/models\.py.*|.*\/models\/.*)'
